Bump actions
kazukazuinaina/dotfiles pull request #9
Opened 2022-11-24 03:09 UTC by uhooi

2022-12-04 10:28 UTC, get-me-power requested changes

2022-12-04 10:28 UTC, get-me-power commented on .github/workflows/vint.yml
> -      uses: actions/setup-python@v1
I prefer to specify main

2022-12-04 10:50 UTC, uhooi commented on .github/workflows/vint.yml
> -      uses: actions/setup-python@v1
```suggestion
      uses: actions/setup-python@main
```

2023-09-09 10:10 UTC, get-me-power approved these changes

2023-09-09 10:10 UTC, merged